### ISSUE TITLE
Chinese character is shown as a blank grid

### ISSUE THREAD

**Issue by RogerCV** [JarveeLee/SynthText_Chinese_version#24]
![Uploading 2017-11-13 15-00-38屏幕截图.png…]()

**Comment by 1LOVESJohnny** [comment]
Hi, 请问您如何解决这个问题？我也遇到一样的情况

**Comment by 1LOVESJohnny** [comment]
I've found a solution. This situation happens when the specific font type is not supported by the local system.
I'm using Ubuntu16.04, so I copied all the font files under data/fonts/*.ttf, *.otf, *.ttc, etc. into system font folder.

`sudo cp ~/SynthText_Chinese_version/data/fonts/ubuntucondensed/*.ttf /usr/share/fonts/opentype/noto/`

and type command as,
`sudo dpkg-reconfigure fontconfig`

and wait for a while then type,
`fc-cache -vf`

After doing all these operations, regenerate the .h5 file and save the image files. All the characters will be shown normally :)
